fix: Multiselect - Deselect icon stays positioned in upper right corner even with multiline text
cfpb/design-system pull request #1803
Opened 2023-11-03 21:33 UTC by meissadia

Bug introduced in https://github.com/cfpb/design-system/pull/1777

## Screenshots
![Screenshot 2023-11-03 at 3 27 04 PM](https://github.com/cfpb/design-system/assets/2592907/edb521b8-c025-4aa3-adc4-a4edcc5b0def)

2023-11-03 21:46 UTC, natalia-fitzgerald requested changes
@meissadia - The placement of the "x" looks good. Instead of centering the text that wraps is it possible to left align it?

2023-11-06 15:50 UTC, natalia-fitzgerald commented
@meissadia 
I have some pending questions on our implementation: 
- Does the tag have a max width of 670px? 
- How about the input field? Or does the input field fill the width of the container less padding? 
- Is stacking the tags vertically or displaying them horizontally both options that can be turned on or off?

2023-11-06 17:59 UTC, natalia-fitzgerald commented
@meissadia 
Is vertical stacking possible to control (in other words one tag per line)?

2023-11-06 18:55 UTC, billhimmelsbach commented
Just adding our discussion here for context:

![Screenshot 2023-11-06 at 10 55 28 AM](https://github.com/cfpb/design-system/assets/19983248/81e3a4b6-f09c-4da6-8a34-67df6f90f6eb)

2023-11-06 20:11 UTC, natalia-fitzgerald approved these changes
Approved. Let's wait to implement the stacking / side-by-side feature until we can publish our current changes to npm.

2023-11-06 20:32 UTC, merged