Styling: Hover/Focus on TextInputs utilize dark colors
cfpb/design-system pull request #1886
Opened 2024-01-19 17:30 UTC by shindigira

closes #1881 

## Changes
- Added new dark hover/focus colors to variables.md
- Added new dark hover/focus colors to text-inputs.md
- Updated text-inputs.md with the new dark hover/focus color stories

## How to Test 
- Test Link: https://deploy-preview-1886--cfpb-design-system.netlify.app/design-system/components/text-inputs
- **Code inspect** `text-inputs.less` and ensure no unintended styling changes affect other components
- Navigate to the `Variables` story section to view the new styling variables.
- **Navigate to the `TextInputs` story section and view the new dark hover/focus styles**. Hover and focus in the three normal status sections (success/error/warning)

## Screenshot(s)

Subtle dark colors -- only visible during hover (not focus)

|Before|After|
|---|---|
|<img width="204" alt="Screenshot 2024-01-22 at 3 43 24 AM" src="https://github.com/cfpb/design-system/assets/13324863/ed1d4083-8ac9-4827-991c-1a87d04c46df">|<img width="205" alt="Screenshot 2024-01-22 at 4 15 28 AM" src="https://github.com/cfpb/design-system/assets/13324863/bab0aacb-9cda-4fce-84f7-f2d888efeca6">|

2024-01-19 20:21 UTC, natalia-fitzgerald requested changes
@shindigira 
When I reviewed this with the design team we had only discussed changing the hover state to the darker color. Changing the focus state (or hover + focus) to the darker color was not the intent and would require further exploration/consideration. Perhaps as a first step we can change the hover to red (instead of blue) and put this additional change aside until I have time to discuss with the team next week? 

Or we can pause on this and focus on the checkbox Error status states as a first step.

2024-01-19 21:07 UTC, anselmbradford commented on packages/cfpb-forms/src/atoms/text-input.less
> +.border-outline-error {
For helper mixins like this we sometimes prefix them with `u-` to indicate that it's a one-off utility thing. I think that would help with these border helpers you have here. See a similar example usage in https://github.com/cfpb/design-system/blob/main/packages/cfpb-typography/src/atoms/links.less#L66

2024-01-19 22:03 UTC, natalia-fitzgerald commented
@shindigira 

I'd like to proceed as follows: 
- Default: Red 
- Hover: Dark Red
- Hover + Focus: Red
- Focus: Red

Thanks!

2024-03-14 18:43 UTC, natalia-fitzgerald approved these changes
Looks great! Nice work @shindigira.

2024-05-03 21:28 UTC, anselmbradford commented
I'll merge this after https://github.com/cfpb/design-system/pull/1973 goes in.

2024-05-07 13:14 UTC, merged